import { Legends } from "../TerminalText";

export const ddriveContents = {
  anomally: {
    redacted: [
      "+---------------------------------------------------------------",
      Legends.NewLine,
      `| Date: ${new Date("1981-01-31").toLocaleDateString()}`,
      Legends.NewLine,
      "| Subject: Recent Unidentified Anomaly",
      Legends.NewLine,
      "+---------------------------------------------------------------",
      Legends.NewLine,
      Legends.NewLine,
      "I am writing to report a series of unsettling and enigmatic events that have been occurring in ████████ over the past week.",
      Legends.NewLine,
      "Our team has closely monitored these activities, but we remain puzzled and unable to ascertain the origin or nature of these incidents.",
      Legends.NewLine,
      Legends.NewLine,
      "Unidentified Movements: Our sensors have detected sporadic movements in various sections of █████████, especially during the late hours of the night.",
      Legends.NewLine,
      "The movements are swift, seemingly erratic and █████████ ████ ██████, making it challenging to track or predict their pattern.",
      Legends.NewLine,
      Legends.NewLine,
      "Rest assured, the crew is committed to resolving this enigma promptly and maintaining the integrity of our facility.",
      Legends.NewLine,
      Legends.NewLine,
      "Sincerely,",
      Legends.NewLine,
      "██████ ██████████",
    ],
    cleaned: [
      "+---------------------------------------------------------------",
      Legends.NewLine,
      `| Date: ${new Date("1981-01-31").toLocaleDateString()}`,
      Legends.NewLine,
      "| Subject: Recent Unidentified Anomaly",
      Legends.NewLine,
      "+---------------------------------------------------------------",
      Legends.NewLine,
      Legends.NewLine,
      "I am writing to report a series of unsettling and enigmatic events that have been occurring in [THE VENTILATIONS] over the past week.",
      Legends.NewLine,
      "Our team has closely monitored these activities, but we remain puzzled and unable to ascertain the origin or nature of these incidents.",
      Legends.NewLine,
      Legends.NewLine,
      "Unidentified Movements: Our sensors have detected sporadic movements in various sections of [VENTIALTIONS IN MECHANIC], especially during the late hours of the night.",
      Legends.NewLine,
      "The movements are swift, seemingly erratic and [SOMETHING REVEALING], making it challenging to track or predict their pattern.",
      Legends.NewLine,
      Legends.NewLine,
      "Rest assured, the crew is committed to resolving this enigma promptly and maintaining the integrity of our facility.",
      Legends.NewLine,
      Legends.NewLine,
      "Sincerely,",
      Legends.NewLine,
      "[BILL PHILLIPS, MECHANICS]",
    ],
  },
};
